rollout:
  image: "quay.io/devtron/rollout:v0.6.2"
  resources:
    limits:
      memory: 200Mi
      cpu: 250m
    requests:
      memory: 100Mi
      cpu: 50m
tolerations: []
podLabels: {}
podAnnotations: {}
replicaCount: 1
serviceMonitor:
  enabled: false
  labels:
    app: argo-rollouts
    kind: Prometheus
    release: monitoring
  endpoints:
  - interval: 50s
    path: /metrics
    port: metrics
    scheme: http
    scrapeTimeout: 9s
  matchLabels:
    app.kubernetes.io/name: argo-rollouts-metrics