rollout:
  image: "quay.io/devtron/rollout:v0.6.2"
  resources:
    limits:
      memory: 200Mi
      cpu: 250m
    requests:
      memory: 100Mi
      cpu: 50m
tolerations: []
podLabels: {}
podAnnotations: {}
replicaCount: 1
serviceMonitorEnabled: false
servicemonitorLabels: 
  app: argo-rollouts
  kind: Prometheus
  release: monitoring