{{- if $.Values.alert.enabled -}}
{{- if .Capabilities.APIVersions.Has "batch/v1/CronJob" }}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: argocd-cert-alert
spec:
  schedule: {{ $.Values.alert.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          {{- if  $.Values.podSecurityContext }}
          securityContext: 
{{ toYaml $.Values.podSecurityContext | indent 12 }}      
          {{- end }}
          serviceAccountName: argocd-cert-sa
          serviceAccount: argocd-cert-sa
          containers:
          - name: argocd-alert-container
            image:  {{ $.Values.alert.image }}
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh", "-c", "chmod +x alert.sh && ./alert.sh"]
            env:
              - name: discord_url
                value: {{$.Values.alert.discord_url | quote }}
              - name: alert_before
                value: {{$.Values.alert.alert_before | quote}}
            {{- if $.Values.containerSecurityContext }}
            securityContext: 
{{ toYaml $.Values.containerSecurityContext | indent 14 }}         
            {{- end}}
          restartPolicy: OnFailure
{{- end }}