apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-cert-role
  namespace: {{ $.Values.argocd_namespace| default .Release.Namespace }}
rules:
- apiGroups: 
    - ""
    - batch
    - apps
  resources:
  - pods
  - secrets
  - cronjobs
  - deployments
  verbs:
  - create
  - get
  - watch
  - list
  - delete
  - update
  - patch