{{- if .Capabilities.APIVersions.Has "batch/v1/CronJob" }}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: argocd-cert-cronjob
spec:
  schedule: {{ $.Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          {{- if  $.Values.podSecurityContext }}
          securityContext: 
{{ toYaml $.Values.podSecurityContext | indent 12 }}      
          {{- end }}
          serviceAccountName: argocd-cert-sa
          serviceAccount: argocd-cert-sa
          containers:
          - name: argocd-cert-con
            image: {{ $.Values.image }}
            imagePullPolicy: IfNotPresent
            command: ["./argocd.sh"]
            {{- if $.Values.containerSecurityContext }}
            securityContext: 
{{ toYaml $.Values.containerSecurityContext | indent 14 }}         
            {{- end}}
            restartPolicy: OnFailure