{{- if .Values.global.S3.enabled }}
{{- if or .Values.postgres_backup.enabled .Values.argocd_backup.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: devtron-s3-backup-secret
type: opaque
data:
    S3_BUCKET_NAME: {{ .Values.global.S3.S3_BUCKET_NAME | b64enc }}
    AWS_ACCESS_KEY: {{ .Values.global.S3.S3_ACCESS_KEY | b64enc }}
    AWS_SECRET_KEY: {{ .Values.global.S3.S3_SECRET_KEY | b64enc }}
    AWS_REGION: {{ .Values.global.S3.AWS_REGION | default "us-east-1" | b64enc }}
{{- end }}
{{- end }}