{{- if .Values.global.AZURE.enabled }}
{{- if or .Values.postgres_backup.enabled .Values.argocd_backup.enabled }} 
apiVersion: v1
kind: Secret
metadata:
  name: devtron-azure-backup-secret
type: opaque
data:
    AZURE_BLOB_ACCOUNT_NAME: {{ .Values.global.AZURE.AZURE_BLOB_ACCOUNT_NAME | b64enc }}
    AZURE_ACCOUNT_KEY: {{ .Values.global.AZURE.AZURE_ACCOUNT_KEY | b64enc }}
    AZURE_BLOB_CONTAINER_FOR_POSTGRES: {{ .Values.global.AZURE.AZURE_BLOB_CONTAINER_FOR_POSTGRES | b64enc }}
    AZURE_BLOB_CONTAINER_FOR_ARGOCD: {{ .Values.global.AZURE.AZURE_BLOB_CONTAINER_FOR_ARGOCD | b64enc }}
{{- end }}
{{- end }}