# Default values for argocd-certificate-refresh.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# docker image information
image: quay.io/devtron/test:a2a56bd1-555-21342





# values for cronjob
cronjob:
  schedule: "59 23 1 */6 *"




#set up this If you need alert for argocd cert expire
alert:
  enabled: false
  image: quay.io/devtron/test:578de80c-489-21336
  discord_url: "" 
  schedule: "30 12 * * *"
  # if the certificate will expire after 10 days you will get alert
  alert_before: 10
  # if the next cron will be run after 2 days you will get alert
  cronJobRunAfter: 2



podSecurityContext: {}
  # runAsGroup: 1000
  # runAsUser: 1000
containerSecurityContext: {}
    # allowPrivilegeEscalation: false
    # runAsUser: 1000
    # runAsNonRoot: true
